// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: business.proto

package com.treeleaf.suchi.entities;

public final class BusinessProto {
  private BusinessProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code com.entities.pb.BusinessStatus}
   */
  public enum BusinessStatus
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_BUSINESS_STATUS = 0;</code>
     */
    UNKNOWN_BUSINESS_STATUS(0),
    /**
     * <code>ACTIVE = 1;</code>
     */
    ACTIVE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_BUSINESS_STATUS = 0;</code>
     */
    public static final int UNKNOWN_BUSINESS_STATUS_VALUE = 0;
    /**
     * <code>ACTIVE = 1;</code>
     */
    public static final int ACTIVE_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static BusinessStatus valueOf(int value) {
      return forNumber(value);
    }

    public static BusinessStatus forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_BUSINESS_STATUS;
        case 1: return ACTIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BusinessStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BusinessStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BusinessStatus>() {
            public BusinessStatus findValueByNumber(int number) {
              return BusinessStatus.forNumber(number);
            }
          };

    private final int value;

    private BusinessStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.entities.pb.BusinessStatus)
  }

  /**
   * Protobuf enum {@code com.entities.pb.SKUStatus}
   */
  public enum SKUStatus
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_KYU_STATUS = 0;</code>
     */
    UNKNOWN_KYU_STATUS(0),
    /**
     * <code>AVAILABLE = 1;</code>
     */
    AVAILABLE(1),
    /**
     * <code>UNAVAILABLE = 2;</code>
     */
    UNAVAILABLE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_KYU_STATUS = 0;</code>
     */
    public static final int UNKNOWN_KYU_STATUS_VALUE = 0;
    /**
     * <code>AVAILABLE = 1;</code>
     */
    public static final int AVAILABLE_VALUE = 1;
    /**
     * <code>UNAVAILABLE = 2;</code>
     */
    public static final int UNAVAILABLE_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static SKUStatus valueOf(int value) {
      return forNumber(value);
    }

    public static SKUStatus forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_KYU_STATUS;
        case 1: return AVAILABLE;
        case 2: return UNAVAILABLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SKUStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SKUStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SKUStatus>() {
            public SKUStatus findValueByNumber(int number) {
              return SKUStatus.forNumber(number);
            }
          };

    private final int value;

    private SKUStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.entities.pb.SKUStatus)
  }

  public interface StockKeepingUnitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.entities.pb.StockKeepingUnit)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string skyId = 1;</code>
     */
    String getSkyId();
    /**
     * <code>optional string skyId = 1;</code>
     */
    com.google.protobuf.ByteString
        getSkyIdBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string photo = 3;</code>
     */
    String getPhoto();
    /**
     * <code>optional string photo = 3;</code>
     */
    com.google.protobuf.ByteString
        getPhotoBytes();

    /**
     * <code>optional string brand = 4;</code>
     */
    String getBrand();
    /**
     * <code>optional string brand = 4;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>optional string code = 5;</code>
     */
    String getCode();
    /**
     * <code>optional string code = 5;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>optional int32 quantity = 6;</code>
     */
    int getQuantity();

    /**
     * <code>optional int64 expiryDate = 7;</code>
     */
    long getExpiryDate();

    /**
     * <code>optional string description = 8;</code>
     */
    String getDescription();
    /**
     * <code>optional string description = 8;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional double unitPrice = 9;</code>
     */
    double getUnitPrice();

    /**
     * <code>optional .com.entities.pb.SKUStatus status = 10;</code>
     */
    int getStatusValue();
    /**
     * <code>optional .com.entities.pb.SKUStatus status = 10;</code>
     */
    com.treeleaf.suchi.entities.BusinessProto.SKUStatus getStatus();
  }
  /**
   * Protobuf type {@code com.entities.pb.StockKeepingUnit}
   */
  public  static final class StockKeepingUnit extends
      com.google.protobuf.GeneratedMessageLite<
          StockKeepingUnit, StockKeepingUnit.Builder> implements
      // @@protoc_insertion_point(message_implements:com.entities.pb.StockKeepingUnit)
      StockKeepingUnitOrBuilder {
    private StockKeepingUnit() {
      skyId_ = "";
      name_ = "";
      photo_ = "";
      brand_ = "";
      code_ = "";
      description_ = "";
    }
    public static final int SKYID_FIELD_NUMBER = 1;
    private String skyId_;
    /**
     * <code>optional string skyId = 1;</code>
     */
    public String getSkyId() {
      return skyId_;
    }
    /**
     * <code>optional string skyId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSkyIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(skyId_);
    }
    /**
     * <code>optional string skyId = 1;</code>
     */
    private void setSkyId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      skyId_ = value;
    }
    /**
     * <code>optional string skyId = 1;</code>
     */
    private void clearSkyId() {
      
      skyId_ = getDefaultInstance().getSkyId();
    }
    /**
     * <code>optional string skyId = 1;</code>
     */
    private void setSkyIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      skyId_ = value.toStringUtf8();
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private String name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public String getName() {
      return name_;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    private void setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>optional string name = 2;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int PHOTO_FIELD_NUMBER = 3;
    private String photo_;
    /**
     * <code>optional string photo = 3;</code>
     */
    public String getPhoto() {
      return photo_;
    }
    /**
     * <code>optional string photo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhotoBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(photo_);
    }
    /**
     * <code>optional string photo = 3;</code>
     */
    private void setPhoto(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      photo_ = value;
    }
    /**
     * <code>optional string photo = 3;</code>
     */
    private void clearPhoto() {
      
      photo_ = getDefaultInstance().getPhoto();
    }
    /**
     * <code>optional string photo = 3;</code>
     */
    private void setPhotoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      photo_ = value.toStringUtf8();
    }

    public static final int BRAND_FIELD_NUMBER = 4;
    private String brand_;
    /**
     * <code>optional string brand = 4;</code>
     */
    public String getBrand() {
      return brand_;
    }
    /**
     * <code>optional string brand = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(brand_);
    }
    /**
     * <code>optional string brand = 4;</code>
     */
    private void setBrand(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      brand_ = value;
    }
    /**
     * <code>optional string brand = 4;</code>
     */
    private void clearBrand() {
      
      brand_ = getDefaultInstance().getBrand();
    }
    /**
     * <code>optional string brand = 4;</code>
     */
    private void setBrandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      brand_ = value.toStringUtf8();
    }

    public static final int CODE_FIELD_NUMBER = 5;
    private String code_;
    /**
     * <code>optional string code = 5;</code>
     */
    public String getCode() {
      return code_;
    }
    /**
     * <code>optional string code = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(code_);
    }
    /**
     * <code>optional string code = 5;</code>
     */
    private void setCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      code_ = value;
    }
    /**
     * <code>optional string code = 5;</code>
     */
    private void clearCode() {
      
      code_ = getDefaultInstance().getCode();
    }
    /**
     * <code>optional string code = 5;</code>
     */
    private void setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      code_ = value.toStringUtf8();
    }

    public static final int QUANTITY_FIELD_NUMBER = 6;
    private int quantity_;
    /**
     * <code>optional int32 quantity = 6;</code>
     */
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>optional int32 quantity = 6;</code>
     */
    private void setQuantity(int value) {
      
      quantity_ = value;
    }
    /**
     * <code>optional int32 quantity = 6;</code>
     */
    private void clearQuantity() {
      
      quantity_ = 0;
    }

    public static final int EXPIRYDATE_FIELD_NUMBER = 7;
    private long expiryDate_;
    /**
     * <code>optional int64 expiryDate = 7;</code>
     */
    public long getExpiryDate() {
      return expiryDate_;
    }
    /**
     * <code>optional int64 expiryDate = 7;</code>
     */
    private void setExpiryDate(long value) {
      
      expiryDate_ = value;
    }
    /**
     * <code>optional int64 expiryDate = 7;</code>
     */
    private void clearExpiryDate() {
      
      expiryDate_ = 0L;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 8;
    private String description_;
    /**
     * <code>optional string description = 8;</code>
     */
    public String getDescription() {
      return description_;
    }
    /**
     * <code>optional string description = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(description_);
    }
    /**
     * <code>optional string description = 8;</code>
     */
    private void setDescription(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
    }
    /**
     * <code>optional string description = 8;</code>
     */
    private void clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
    }
    /**
     * <code>optional string description = 8;</code>
     */
    private void setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value.toStringUtf8();
    }

    public static final int UNITPRICE_FIELD_NUMBER = 9;
    private double unitPrice_;
    /**
     * <code>optional double unitPrice = 9;</code>
     */
    public double getUnitPrice() {
      return unitPrice_;
    }
    /**
     * <code>optional double unitPrice = 9;</code>
     */
    private void setUnitPrice(double value) {
      
      unitPrice_ = value;
    }
    /**
     * <code>optional double unitPrice = 9;</code>
     */
    private void clearUnitPrice() {
      
      unitPrice_ = 0D;
    }

    public static final int STATUS_FIELD_NUMBER = 10;
    private int status_;
    /**
     * <code>optional .com.entities.pb.SKUStatus status = 10;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .com.entities.pb.SKUStatus status = 10;</code>
     */
    public com.treeleaf.suchi.entities.BusinessProto.SKUStatus getStatus() {
      com.treeleaf.suchi.entities.BusinessProto.SKUStatus result = com.treeleaf.suchi.entities.BusinessProto.SKUStatus.forNumber(status_);
      return result == null ? com.treeleaf.suchi.entities.BusinessProto.SKUStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.entities.pb.SKUStatus status = 10;</code>
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>optional .com.entities.pb.SKUStatus status = 10;</code>
     */
    private void setStatus(com.treeleaf.suchi.entities.BusinessProto.SKUStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
    }
    /**
     * <code>optional .com.entities.pb.SKUStatus status = 10;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!skyId_.isEmpty()) {
        output.writeString(1, getSkyId());
      }
      if (!name_.isEmpty()) {
        output.writeString(2, getName());
      }
      if (!photo_.isEmpty()) {
        output.writeString(3, getPhoto());
      }
      if (!brand_.isEmpty()) {
        output.writeString(4, getBrand());
      }
      if (!code_.isEmpty()) {
        output.writeString(5, getCode());
      }
      if (quantity_ != 0) {
        output.writeInt32(6, quantity_);
      }
      if (expiryDate_ != 0L) {
        output.writeInt64(7, expiryDate_);
      }
      if (!description_.isEmpty()) {
        output.writeString(8, getDescription());
      }
      if (unitPrice_ != 0D) {
        output.writeDouble(9, unitPrice_);
      }
      if (status_ != com.treeleaf.suchi.entities.BusinessProto.SKUStatus.UNKNOWN_KYU_STATUS.getNumber()) {
        output.writeEnum(10, status_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!skyId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSkyId());
      }
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (!photo_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getPhoto());
      }
      if (!brand_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getBrand());
      }
      if (!code_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getCode());
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, quantity_);
      }
      if (expiryDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, expiryDate_);
      }
      if (!description_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getDescription());
      }
      if (unitPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, unitPrice_);
      }
      if (status_ != com.treeleaf.suchi.entities.BusinessProto.SKUStatus.UNKNOWN_KYU_STATUS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, status_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.entities.pb.StockKeepingUnit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.entities.pb.StockKeepingUnit)
        com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnitOrBuilder {
      // Construct using com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string skyId = 1;</code>
       */
      public String getSkyId() {
        return instance.getSkyId();
      }
      /**
       * <code>optional string skyId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSkyIdBytes() {
        return instance.getSkyIdBytes();
      }
      /**
       * <code>optional string skyId = 1;</code>
       */
      public Builder setSkyId(
          String value) {
        copyOnWrite();
        instance.setSkyId(value);
        return this;
      }
      /**
       * <code>optional string skyId = 1;</code>
       */
      public Builder clearSkyId() {
        copyOnWrite();
        instance.clearSkyId();
        return this;
      }
      /**
       * <code>optional string skyId = 1;</code>
       */
      public Builder setSkyIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSkyIdBytes(value);
        return this;
      }

      /**
       * <code>optional string name = 2;</code>
       */
      public String getName() {
        return instance.getName();
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>optional string photo = 3;</code>
       */
      public String getPhoto() {
        return instance.getPhoto();
      }
      /**
       * <code>optional string photo = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhotoBytes() {
        return instance.getPhotoBytes();
      }
      /**
       * <code>optional string photo = 3;</code>
       */
      public Builder setPhoto(
          String value) {
        copyOnWrite();
        instance.setPhoto(value);
        return this;
      }
      /**
       * <code>optional string photo = 3;</code>
       */
      public Builder clearPhoto() {
        copyOnWrite();
        instance.clearPhoto();
        return this;
      }
      /**
       * <code>optional string photo = 3;</code>
       */
      public Builder setPhotoBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPhotoBytes(value);
        return this;
      }

      /**
       * <code>optional string brand = 4;</code>
       */
      public String getBrand() {
        return instance.getBrand();
      }
      /**
       * <code>optional string brand = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        return instance.getBrandBytes();
      }
      /**
       * <code>optional string brand = 4;</code>
       */
      public Builder setBrand(
          String value) {
        copyOnWrite();
        instance.setBrand(value);
        return this;
      }
      /**
       * <code>optional string brand = 4;</code>
       */
      public Builder clearBrand() {
        copyOnWrite();
        instance.clearBrand();
        return this;
      }
      /**
       * <code>optional string brand = 4;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBrandBytes(value);
        return this;
      }

      /**
       * <code>optional string code = 5;</code>
       */
      public String getCode() {
        return instance.getCode();
      }
      /**
       * <code>optional string code = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        return instance.getCodeBytes();
      }
      /**
       * <code>optional string code = 5;</code>
       */
      public Builder setCode(
          String value) {
        copyOnWrite();
        instance.setCode(value);
        return this;
      }
      /**
       * <code>optional string code = 5;</code>
       */
      public Builder clearCode() {
        copyOnWrite();
        instance.clearCode();
        return this;
      }
      /**
       * <code>optional string code = 5;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCodeBytes(value);
        return this;
      }

      /**
       * <code>optional int32 quantity = 6;</code>
       */
      public int getQuantity() {
        return instance.getQuantity();
      }
      /**
       * <code>optional int32 quantity = 6;</code>
       */
      public Builder setQuantity(int value) {
        copyOnWrite();
        instance.setQuantity(value);
        return this;
      }
      /**
       * <code>optional int32 quantity = 6;</code>
       */
      public Builder clearQuantity() {
        copyOnWrite();
        instance.clearQuantity();
        return this;
      }

      /**
       * <code>optional int64 expiryDate = 7;</code>
       */
      public long getExpiryDate() {
        return instance.getExpiryDate();
      }
      /**
       * <code>optional int64 expiryDate = 7;</code>
       */
      public Builder setExpiryDate(long value) {
        copyOnWrite();
        instance.setExpiryDate(value);
        return this;
      }
      /**
       * <code>optional int64 expiryDate = 7;</code>
       */
      public Builder clearExpiryDate() {
        copyOnWrite();
        instance.clearExpiryDate();
        return this;
      }

      /**
       * <code>optional string description = 8;</code>
       */
      public String getDescription() {
        return instance.getDescription();
      }
      /**
       * <code>optional string description = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        return instance.getDescriptionBytes();
      }
      /**
       * <code>optional string description = 8;</code>
       */
      public Builder setDescription(
          String value) {
        copyOnWrite();
        instance.setDescription(value);
        return this;
      }
      /**
       * <code>optional string description = 8;</code>
       */
      public Builder clearDescription() {
        copyOnWrite();
        instance.clearDescription();
        return this;
      }
      /**
       * <code>optional string description = 8;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDescriptionBytes(value);
        return this;
      }

      /**
       * <code>optional double unitPrice = 9;</code>
       */
      public double getUnitPrice() {
        return instance.getUnitPrice();
      }
      /**
       * <code>optional double unitPrice = 9;</code>
       */
      public Builder setUnitPrice(double value) {
        copyOnWrite();
        instance.setUnitPrice(value);
        return this;
      }
      /**
       * <code>optional double unitPrice = 9;</code>
       */
      public Builder clearUnitPrice() {
        copyOnWrite();
        instance.clearUnitPrice();
        return this;
      }

      /**
       * <code>optional .com.entities.pb.SKUStatus status = 10;</code>
       */
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>optional .com.entities.pb.SKUStatus status = 10;</code>
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>optional .com.entities.pb.SKUStatus status = 10;</code>
       */
      public com.treeleaf.suchi.entities.BusinessProto.SKUStatus getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>optional .com.entities.pb.SKUStatus status = 10;</code>
       */
      public Builder setStatus(com.treeleaf.suchi.entities.BusinessProto.SKUStatus value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>optional .com.entities.pb.SKUStatus status = 10;</code>
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.entities.pb.StockKeepingUnit)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit other = (com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit) arg1;
          skyId_ = visitor.visitString(!skyId_.isEmpty(), skyId_,
              !other.skyId_.isEmpty(), other.skyId_);
          name_ = visitor.visitString(!name_.isEmpty(), name_,
              !other.name_.isEmpty(), other.name_);
          photo_ = visitor.visitString(!photo_.isEmpty(), photo_,
              !other.photo_.isEmpty(), other.photo_);
          brand_ = visitor.visitString(!brand_.isEmpty(), brand_,
              !other.brand_.isEmpty(), other.brand_);
          code_ = visitor.visitString(!code_.isEmpty(), code_,
              !other.code_.isEmpty(), other.code_);
          quantity_ = visitor.visitInt(quantity_ != 0, quantity_,
              other.quantity_ != 0, other.quantity_);
          expiryDate_ = visitor.visitLong(expiryDate_ != 0L, expiryDate_,
              other.expiryDate_ != 0L, other.expiryDate_);
          description_ = visitor.visitString(!description_.isEmpty(), description_,
              !other.description_.isEmpty(), other.description_);
          unitPrice_ = visitor.visitDouble(unitPrice_ != 0D, unitPrice_,
              other.unitPrice_ != 0D, other.unitPrice_);
          status_ = visitor.visitInt(status_ != 0, status_,    other.status_ != 0, other.status_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  skyId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  photo_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  brand_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  code_ = s;
                  break;
                }
                case 48: {

                  quantity_ = input.readInt32();
                  break;
                }
                case 56: {

                  expiryDate_ = input.readInt64();
                  break;
                }
                case 66: {
                  String s = input.readStringRequireUtf8();

                  description_ = s;
                  break;
                }
                case 73: {

                  unitPrice_ = input.readDouble();
                  break;
                }
                case 80: {
                  int rawValue = input.readEnum();

                  status_ = rawValue;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.entities.pb.StockKeepingUnit)
    private static final com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StockKeepingUnit();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.treeleaf.suchi.entities.BusinessProto.StockKeepingUnit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<StockKeepingUnit> PARSER;

    public static com.google.protobuf.Parser<StockKeepingUnit> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LicenseKeyManagementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.entities.pb.LicenseKeyManagement)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string licenseKey = 1;</code>
     */
    String getLicenseKey();
    /**
     * <code>optional string licenseKey = 1;</code>
     */
    com.google.protobuf.ByteString
        getLicenseKeyBytes();

    /**
     * <code>optional string panVat = 2;</code>
     */
    String getPanVat();
    /**
     * <code>optional string panVat = 2;</code>
     */
    com.google.protobuf.ByteString
        getPanVatBytes();

    /**
     * <code>optional int64 assignedDate = 3;</code>
     */
    long getAssignedDate();

    /**
     * <code>optional int64 expiryDate = 4;</code>
     */
    long getExpiryDate();
  }
  /**
   * Protobuf type {@code com.entities.pb.LicenseKeyManagement}
   */
  public  static final class LicenseKeyManagement extends
      com.google.protobuf.GeneratedMessageLite<
          LicenseKeyManagement, LicenseKeyManagement.Builder> implements
      // @@protoc_insertion_point(message_implements:com.entities.pb.LicenseKeyManagement)
      LicenseKeyManagementOrBuilder {
    private LicenseKeyManagement() {
      licenseKey_ = "";
      panVat_ = "";
    }
    public static final int LICENSEKEY_FIELD_NUMBER = 1;
    private String licenseKey_;
    /**
     * <code>optional string licenseKey = 1;</code>
     */
    public String getLicenseKey() {
      return licenseKey_;
    }
    /**
     * <code>optional string licenseKey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLicenseKeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(licenseKey_);
    }
    /**
     * <code>optional string licenseKey = 1;</code>
     */
    private void setLicenseKey(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      licenseKey_ = value;
    }
    /**
     * <code>optional string licenseKey = 1;</code>
     */
    private void clearLicenseKey() {
      
      licenseKey_ = getDefaultInstance().getLicenseKey();
    }
    /**
     * <code>optional string licenseKey = 1;</code>
     */
    private void setLicenseKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      licenseKey_ = value.toStringUtf8();
    }

    public static final int PANVAT_FIELD_NUMBER = 2;
    private String panVat_;
    /**
     * <code>optional string panVat = 2;</code>
     */
    public String getPanVat() {
      return panVat_;
    }
    /**
     * <code>optional string panVat = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPanVatBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(panVat_);
    }
    /**
     * <code>optional string panVat = 2;</code>
     */
    private void setPanVat(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      panVat_ = value;
    }
    /**
     * <code>optional string panVat = 2;</code>
     */
    private void clearPanVat() {
      
      panVat_ = getDefaultInstance().getPanVat();
    }
    /**
     * <code>optional string panVat = 2;</code>
     */
    private void setPanVatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      panVat_ = value.toStringUtf8();
    }

    public static final int ASSIGNEDDATE_FIELD_NUMBER = 3;
    private long assignedDate_;
    /**
     * <code>optional int64 assignedDate = 3;</code>
     */
    public long getAssignedDate() {
      return assignedDate_;
    }
    /**
     * <code>optional int64 assignedDate = 3;</code>
     */
    private void setAssignedDate(long value) {
      
      assignedDate_ = value;
    }
    /**
     * <code>optional int64 assignedDate = 3;</code>
     */
    private void clearAssignedDate() {
      
      assignedDate_ = 0L;
    }

    public static final int EXPIRYDATE_FIELD_NUMBER = 4;
    private long expiryDate_;
    /**
     * <code>optional int64 expiryDate = 4;</code>
     */
    public long getExpiryDate() {
      return expiryDate_;
    }
    /**
     * <code>optional int64 expiryDate = 4;</code>
     */
    private void setExpiryDate(long value) {
      
      expiryDate_ = value;
    }
    /**
     * <code>optional int64 expiryDate = 4;</code>
     */
    private void clearExpiryDate() {
      
      expiryDate_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!licenseKey_.isEmpty()) {
        output.writeString(1, getLicenseKey());
      }
      if (!panVat_.isEmpty()) {
        output.writeString(2, getPanVat());
      }
      if (assignedDate_ != 0L) {
        output.writeInt64(3, assignedDate_);
      }
      if (expiryDate_ != 0L) {
        output.writeInt64(4, expiryDate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!licenseKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getLicenseKey());
      }
      if (!panVat_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPanVat());
      }
      if (assignedDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, assignedDate_);
      }
      if (expiryDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, expiryDate_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.entities.pb.LicenseKeyManagement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.entities.pb.LicenseKeyManagement)
        com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagementOrBuilder {
      // Construct using com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string licenseKey = 1;</code>
       */
      public String getLicenseKey() {
        return instance.getLicenseKey();
      }
      /**
       * <code>optional string licenseKey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLicenseKeyBytes() {
        return instance.getLicenseKeyBytes();
      }
      /**
       * <code>optional string licenseKey = 1;</code>
       */
      public Builder setLicenseKey(
          String value) {
        copyOnWrite();
        instance.setLicenseKey(value);
        return this;
      }
      /**
       * <code>optional string licenseKey = 1;</code>
       */
      public Builder clearLicenseKey() {
        copyOnWrite();
        instance.clearLicenseKey();
        return this;
      }
      /**
       * <code>optional string licenseKey = 1;</code>
       */
      public Builder setLicenseKeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLicenseKeyBytes(value);
        return this;
      }

      /**
       * <code>optional string panVat = 2;</code>
       */
      public String getPanVat() {
        return instance.getPanVat();
      }
      /**
       * <code>optional string panVat = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPanVatBytes() {
        return instance.getPanVatBytes();
      }
      /**
       * <code>optional string panVat = 2;</code>
       */
      public Builder setPanVat(
          String value) {
        copyOnWrite();
        instance.setPanVat(value);
        return this;
      }
      /**
       * <code>optional string panVat = 2;</code>
       */
      public Builder clearPanVat() {
        copyOnWrite();
        instance.clearPanVat();
        return this;
      }
      /**
       * <code>optional string panVat = 2;</code>
       */
      public Builder setPanVatBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPanVatBytes(value);
        return this;
      }

      /**
       * <code>optional int64 assignedDate = 3;</code>
       */
      public long getAssignedDate() {
        return instance.getAssignedDate();
      }
      /**
       * <code>optional int64 assignedDate = 3;</code>
       */
      public Builder setAssignedDate(long value) {
        copyOnWrite();
        instance.setAssignedDate(value);
        return this;
      }
      /**
       * <code>optional int64 assignedDate = 3;</code>
       */
      public Builder clearAssignedDate() {
        copyOnWrite();
        instance.clearAssignedDate();
        return this;
      }

      /**
       * <code>optional int64 expiryDate = 4;</code>
       */
      public long getExpiryDate() {
        return instance.getExpiryDate();
      }
      /**
       * <code>optional int64 expiryDate = 4;</code>
       */
      public Builder setExpiryDate(long value) {
        copyOnWrite();
        instance.setExpiryDate(value);
        return this;
      }
      /**
       * <code>optional int64 expiryDate = 4;</code>
       */
      public Builder clearExpiryDate() {
        copyOnWrite();
        instance.clearExpiryDate();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.entities.pb.LicenseKeyManagement)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement other = (com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement) arg1;
          licenseKey_ = visitor.visitString(!licenseKey_.isEmpty(), licenseKey_,
              !other.licenseKey_.isEmpty(), other.licenseKey_);
          panVat_ = visitor.visitString(!panVat_.isEmpty(), panVat_,
              !other.panVat_.isEmpty(), other.panVat_);
          assignedDate_ = visitor.visitLong(assignedDate_ != 0L, assignedDate_,
              other.assignedDate_ != 0L, other.assignedDate_);
          expiryDate_ = visitor.visitLong(expiryDate_ != 0L, expiryDate_,
              other.expiryDate_ != 0L, other.expiryDate_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  licenseKey_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  panVat_ = s;
                  break;
                }
                case 24: {

                  assignedDate_ = input.readInt64();
                  break;
                }
                case 32: {

                  expiryDate_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.entities.pb.LicenseKeyManagement)
    private static final com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LicenseKeyManagement();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.treeleaf.suchi.entities.BusinessProto.LicenseKeyManagement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LicenseKeyManagement> PARSER;

    public static com.google.protobuf.Parser<LicenseKeyManagement> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface BusinessOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.entities.pb.Business)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string panVat = 1;</code>
     */
    String getPanVat();
    /**
     * <code>optional string panVat = 1;</code>
     */
    com.google.protobuf.ByteString
        getPanVatBytes();

    /**
     * <code>optional string address = 2;</code>
     */
    String getAddress();
    /**
     * <code>optional string address = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>optional int64 registeredDate = 3;</code>
     */
    long getRegisteredDate();

    /**
     * <code>optional string contact = 4;</code>
     */
    String getContact();
    /**
     * <code>optional string contact = 4;</code>
     */
    com.google.protobuf.ByteString
        getContactBytes();

    /**
     * <code>optional .com.entities.pb.User user = 5;</code>
     */
    boolean hasUser();
    /**
     * <code>optional .com.entities.pb.User user = 5;</code>
     */
    com.treeleaf.suchi.entities.AccountProto.User getUser();

    /**
     * <code>optional string businessName = 6;</code>
     */
    String getBusinessName();
    /**
     * <code>optional string businessName = 6;</code>
     */
    com.google.protobuf.ByteString
        getBusinessNameBytes();

    /**
     * <code>optional string description = 7;</code>
     */
    String getDescription();
    /**
     * <code>optional string description = 7;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional .com.entities.pb.BusinessStatus status = 8;</code>
     */
    int getStatusValue();
    /**
     * <code>optional .com.entities.pb.BusinessStatus status = 8;</code>
     */
    com.treeleaf.suchi.entities.BusinessProto.BusinessStatus getStatus();
  }
  /**
   * Protobuf type {@code com.entities.pb.Business}
   */
  public  static final class Business extends
      com.google.protobuf.GeneratedMessageLite<
          Business, Business.Builder> implements
      // @@protoc_insertion_point(message_implements:com.entities.pb.Business)
      BusinessOrBuilder {
    private Business() {
      panVat_ = "";
      address_ = "";
      contact_ = "";
      businessName_ = "";
      description_ = "";
    }
    public static final int PANVAT_FIELD_NUMBER = 1;
    private String panVat_;
    /**
     * <code>optional string panVat = 1;</code>
     */
    public String getPanVat() {
      return panVat_;
    }
    /**
     * <code>optional string panVat = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPanVatBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(panVat_);
    }
    /**
     * <code>optional string panVat = 1;</code>
     */
    private void setPanVat(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      panVat_ = value;
    }
    /**
     * <code>optional string panVat = 1;</code>
     */
    private void clearPanVat() {
      
      panVat_ = getDefaultInstance().getPanVat();
    }
    /**
     * <code>optional string panVat = 1;</code>
     */
    private void setPanVatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      panVat_ = value.toStringUtf8();
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    private String address_;
    /**
     * <code>optional string address = 2;</code>
     */
    public String getAddress() {
      return address_;
    }
    /**
     * <code>optional string address = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(address_);
    }
    /**
     * <code>optional string address = 2;</code>
     */
    private void setAddress(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      address_ = value;
    }
    /**
     * <code>optional string address = 2;</code>
     */
    private void clearAddress() {
      
      address_ = getDefaultInstance().getAddress();
    }
    /**
     * <code>optional string address = 2;</code>
     */
    private void setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      address_ = value.toStringUtf8();
    }

    public static final int REGISTEREDDATE_FIELD_NUMBER = 3;
    private long registeredDate_;
    /**
     * <code>optional int64 registeredDate = 3;</code>
     */
    public long getRegisteredDate() {
      return registeredDate_;
    }
    /**
     * <code>optional int64 registeredDate = 3;</code>
     */
    private void setRegisteredDate(long value) {
      
      registeredDate_ = value;
    }
    /**
     * <code>optional int64 registeredDate = 3;</code>
     */
    private void clearRegisteredDate() {
      
      registeredDate_ = 0L;
    }

    public static final int CONTACT_FIELD_NUMBER = 4;
    private String contact_;
    /**
     * <code>optional string contact = 4;</code>
     */
    public String getContact() {
      return contact_;
    }
    /**
     * <code>optional string contact = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContactBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(contact_);
    }
    /**
     * <code>optional string contact = 4;</code>
     */
    private void setContact(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contact_ = value;
    }
    /**
     * <code>optional string contact = 4;</code>
     */
    private void clearContact() {
      
      contact_ = getDefaultInstance().getContact();
    }
    /**
     * <code>optional string contact = 4;</code>
     */
    private void setContactBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contact_ = value.toStringUtf8();
    }

    public static final int USER_FIELD_NUMBER = 5;
    private com.treeleaf.suchi.entities.AccountProto.User user_;
    /**
     * <code>optional .com.entities.pb.User user = 5;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>optional .com.entities.pb.User user = 5;</code>
     */
    public com.treeleaf.suchi.entities.AccountProto.User getUser() {
      return user_ == null ? com.treeleaf.suchi.entities.AccountProto.User.getDefaultInstance() : user_;
    }
    /**
     * <code>optional .com.entities.pb.User user = 5;</code>
     */
    private void setUser(com.treeleaf.suchi.entities.AccountProto.User value) {
      if (value == null) {
        throw new NullPointerException();
      }
      user_ = value;
      
      }
    /**
     * <code>optional .com.entities.pb.User user = 5;</code>
     */
    private void setUser(
        com.treeleaf.suchi.entities.AccountProto.User.Builder builderForValue) {
      user_ = builderForValue.build();
      
    }
    /**
     * <code>optional .com.entities.pb.User user = 5;</code>
     */
    private void mergeUser(com.treeleaf.suchi.entities.AccountProto.User value) {
      if (user_ != null &&
          user_ != com.treeleaf.suchi.entities.AccountProto.User.getDefaultInstance()) {
        user_ =
          com.treeleaf.suchi.entities.AccountProto.User.newBuilder(user_).mergeFrom(value).buildPartial();
      } else {
        user_ = value;
      }
      
    }
    /**
     * <code>optional .com.entities.pb.User user = 5;</code>
     */
    private void clearUser() {  user_ = null;
      
    }

    public static final int BUSINESSNAME_FIELD_NUMBER = 6;
    private String businessName_;
    /**
     * <code>optional string businessName = 6;</code>
     */
    public String getBusinessName() {
      return businessName_;
    }
    /**
     * <code>optional string businessName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBusinessNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(businessName_);
    }
    /**
     * <code>optional string businessName = 6;</code>
     */
    private void setBusinessName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      businessName_ = value;
    }
    /**
     * <code>optional string businessName = 6;</code>
     */
    private void clearBusinessName() {
      
      businessName_ = getDefaultInstance().getBusinessName();
    }
    /**
     * <code>optional string businessName = 6;</code>
     */
    private void setBusinessNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      businessName_ = value.toStringUtf8();
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 7;
    private String description_;
    /**
     * <code>optional string description = 7;</code>
     */
    public String getDescription() {
      return description_;
    }
    /**
     * <code>optional string description = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(description_);
    }
    /**
     * <code>optional string description = 7;</code>
     */
    private void setDescription(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
    }
    /**
     * <code>optional string description = 7;</code>
     */
    private void clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
    }
    /**
     * <code>optional string description = 7;</code>
     */
    private void setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value.toStringUtf8();
    }

    public static final int STATUS_FIELD_NUMBER = 8;
    private int status_;
    /**
     * <code>optional .com.entities.pb.BusinessStatus status = 8;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .com.entities.pb.BusinessStatus status = 8;</code>
     */
    public com.treeleaf.suchi.entities.BusinessProto.BusinessStatus getStatus() {
      com.treeleaf.suchi.entities.BusinessProto.BusinessStatus result = com.treeleaf.suchi.entities.BusinessProto.BusinessStatus.forNumber(status_);
      return result == null ? com.treeleaf.suchi.entities.BusinessProto.BusinessStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.entities.pb.BusinessStatus status = 8;</code>
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>optional .com.entities.pb.BusinessStatus status = 8;</code>
     */
    private void setStatus(com.treeleaf.suchi.entities.BusinessProto.BusinessStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
    }
    /**
     * <code>optional .com.entities.pb.BusinessStatus status = 8;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!panVat_.isEmpty()) {
        output.writeString(1, getPanVat());
      }
      if (!address_.isEmpty()) {
        output.writeString(2, getAddress());
      }
      if (registeredDate_ != 0L) {
        output.writeInt64(3, registeredDate_);
      }
      if (!contact_.isEmpty()) {
        output.writeString(4, getContact());
      }
      if (user_ != null) {
        output.writeMessage(5, getUser());
      }
      if (!businessName_.isEmpty()) {
        output.writeString(6, getBusinessName());
      }
      if (!description_.isEmpty()) {
        output.writeString(7, getDescription());
      }
      if (status_ != com.treeleaf.suchi.entities.BusinessProto.BusinessStatus.UNKNOWN_BUSINESS_STATUS.getNumber()) {
        output.writeEnum(8, status_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!panVat_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getPanVat());
      }
      if (!address_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getAddress());
      }
      if (registeredDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, registeredDate_);
      }
      if (!contact_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getContact());
      }
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getUser());
      }
      if (!businessName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getBusinessName());
      }
      if (!description_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getDescription());
      }
      if (status_ != com.treeleaf.suchi.entities.BusinessProto.BusinessStatus.UNKNOWN_BUSINESS_STATUS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, status_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.treeleaf.suchi.entities.BusinessProto.Business parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.Business parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.Business parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.Business parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.Business parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.Business parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.Business parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.Business parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.Business parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.suchi.entities.BusinessProto.Business parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.treeleaf.suchi.entities.BusinessProto.Business prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.entities.pb.Business}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.treeleaf.suchi.entities.BusinessProto.Business, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.entities.pb.Business)
        com.treeleaf.suchi.entities.BusinessProto.BusinessOrBuilder {
      // Construct using com.treeleaf.suchi.entities.BusinessProto.Business.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string panVat = 1;</code>
       */
      public String getPanVat() {
        return instance.getPanVat();
      }
      /**
       * <code>optional string panVat = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPanVatBytes() {
        return instance.getPanVatBytes();
      }
      /**
       * <code>optional string panVat = 1;</code>
       */
      public Builder setPanVat(
          String value) {
        copyOnWrite();
        instance.setPanVat(value);
        return this;
      }
      /**
       * <code>optional string panVat = 1;</code>
       */
      public Builder clearPanVat() {
        copyOnWrite();
        instance.clearPanVat();
        return this;
      }
      /**
       * <code>optional string panVat = 1;</code>
       */
      public Builder setPanVatBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPanVatBytes(value);
        return this;
      }

      /**
       * <code>optional string address = 2;</code>
       */
      public String getAddress() {
        return instance.getAddress();
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        return instance.getAddressBytes();
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public Builder setAddress(
          String value) {
        copyOnWrite();
        instance.setAddress(value);
        return this;
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public Builder clearAddress() {
        copyOnWrite();
        instance.clearAddress();
        return this;
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAddressBytes(value);
        return this;
      }

      /**
       * <code>optional int64 registeredDate = 3;</code>
       */
      public long getRegisteredDate() {
        return instance.getRegisteredDate();
      }
      /**
       * <code>optional int64 registeredDate = 3;</code>
       */
      public Builder setRegisteredDate(long value) {
        copyOnWrite();
        instance.setRegisteredDate(value);
        return this;
      }
      /**
       * <code>optional int64 registeredDate = 3;</code>
       */
      public Builder clearRegisteredDate() {
        copyOnWrite();
        instance.clearRegisteredDate();
        return this;
      }

      /**
       * <code>optional string contact = 4;</code>
       */
      public String getContact() {
        return instance.getContact();
      }
      /**
       * <code>optional string contact = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContactBytes() {
        return instance.getContactBytes();
      }
      /**
       * <code>optional string contact = 4;</code>
       */
      public Builder setContact(
          String value) {
        copyOnWrite();
        instance.setContact(value);
        return this;
      }
      /**
       * <code>optional string contact = 4;</code>
       */
      public Builder clearContact() {
        copyOnWrite();
        instance.clearContact();
        return this;
      }
      /**
       * <code>optional string contact = 4;</code>
       */
      public Builder setContactBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContactBytes(value);
        return this;
      }

      /**
       * <code>optional .com.entities.pb.User user = 5;</code>
       */
      public boolean hasUser() {
        return instance.hasUser();
      }
      /**
       * <code>optional .com.entities.pb.User user = 5;</code>
       */
      public com.treeleaf.suchi.entities.AccountProto.User getUser() {
        return instance.getUser();
      }
      /**
       * <code>optional .com.entities.pb.User user = 5;</code>
       */
      public Builder setUser(com.treeleaf.suchi.entities.AccountProto.User value) {
        copyOnWrite();
        instance.setUser(value);
        return this;
        }
      /**
       * <code>optional .com.entities.pb.User user = 5;</code>
       */
      public Builder setUser(
          com.treeleaf.suchi.entities.AccountProto.User.Builder builderForValue) {
        copyOnWrite();
        instance.setUser(builderForValue);
        return this;
      }
      /**
       * <code>optional .com.entities.pb.User user = 5;</code>
       */
      public Builder mergeUser(com.treeleaf.suchi.entities.AccountProto.User value) {
        copyOnWrite();
        instance.mergeUser(value);
        return this;
      }
      /**
       * <code>optional .com.entities.pb.User user = 5;</code>
       */
      public Builder clearUser() {  copyOnWrite();
        instance.clearUser();
        return this;
      }

      /**
       * <code>optional string businessName = 6;</code>
       */
      public String getBusinessName() {
        return instance.getBusinessName();
      }
      /**
       * <code>optional string businessName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBusinessNameBytes() {
        return instance.getBusinessNameBytes();
      }
      /**
       * <code>optional string businessName = 6;</code>
       */
      public Builder setBusinessName(
          String value) {
        copyOnWrite();
        instance.setBusinessName(value);
        return this;
      }
      /**
       * <code>optional string businessName = 6;</code>
       */
      public Builder clearBusinessName() {
        copyOnWrite();
        instance.clearBusinessName();
        return this;
      }
      /**
       * <code>optional string businessName = 6;</code>
       */
      public Builder setBusinessNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBusinessNameBytes(value);
        return this;
      }

      /**
       * <code>optional string description = 7;</code>
       */
      public String getDescription() {
        return instance.getDescription();
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        return instance.getDescriptionBytes();
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public Builder setDescription(
          String value) {
        copyOnWrite();
        instance.setDescription(value);
        return this;
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public Builder clearDescription() {
        copyOnWrite();
        instance.clearDescription();
        return this;
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDescriptionBytes(value);
        return this;
      }

      /**
       * <code>optional .com.entities.pb.BusinessStatus status = 8;</code>
       */
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>optional .com.entities.pb.BusinessStatus status = 8;</code>
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>optional .com.entities.pb.BusinessStatus status = 8;</code>
       */
      public com.treeleaf.suchi.entities.BusinessProto.BusinessStatus getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>optional .com.entities.pb.BusinessStatus status = 8;</code>
       */
      public Builder setStatus(com.treeleaf.suchi.entities.BusinessProto.BusinessStatus value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>optional .com.entities.pb.BusinessStatus status = 8;</code>
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.entities.pb.Business)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.treeleaf.suchi.entities.BusinessProto.Business();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.treeleaf.suchi.entities.BusinessProto.Business other = (com.treeleaf.suchi.entities.BusinessProto.Business) arg1;
          panVat_ = visitor.visitString(!panVat_.isEmpty(), panVat_,
              !other.panVat_.isEmpty(), other.panVat_);
          address_ = visitor.visitString(!address_.isEmpty(), address_,
              !other.address_.isEmpty(), other.address_);
          registeredDate_ = visitor.visitLong(registeredDate_ != 0L, registeredDate_,
              other.registeredDate_ != 0L, other.registeredDate_);
          contact_ = visitor.visitString(!contact_.isEmpty(), contact_,
              !other.contact_.isEmpty(), other.contact_);
          user_ = visitor.visitMessage(user_, other.user_);
          businessName_ = visitor.visitString(!businessName_.isEmpty(), businessName_,
              !other.businessName_.isEmpty(), other.businessName_);
          description_ = visitor.visitString(!description_.isEmpty(), description_,
              !other.description_.isEmpty(), other.description_);
          status_ = visitor.visitInt(status_ != 0, status_,    other.status_ != 0, other.status_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  panVat_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  address_ = s;
                  break;
                }
                case 24: {

                  registeredDate_ = input.readInt64();
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  contact_ = s;
                  break;
                }
                case 42: {
                  com.treeleaf.suchi.entities.AccountProto.User.Builder subBuilder = null;
                  if (user_ != null) {
                    subBuilder = user_.toBuilder();
                  }
                  user_ = input.readMessage(com.treeleaf.suchi.entities.AccountProto.User.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(user_);
                    user_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  businessName_ = s;
                  break;
                }
                case 58: {
                  String s = input.readStringRequireUtf8();

                  description_ = s;
                  break;
                }
                case 64: {
                  int rawValue = input.readEnum();

                  status_ = rawValue;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.treeleaf.suchi.entities.BusinessProto.Business.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.entities.pb.Business)
    private static final com.treeleaf.suchi.entities.BusinessProto.Business DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Business();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.treeleaf.suchi.entities.BusinessProto.Business getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Business> PARSER;

    public static com.google.protobuf.Parser<Business> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
