// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package com.treeleaf.suchi.entities;

public final class InventoryProto {
  private InventoryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code com.entities.pb.BusinessStatus}
   */
  public enum BusinessStatus
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_BUSINESS_STATUS = 0;</code>
     */
    UNKNOWN_BUSINESS_STATUS(0),
    /**
     * <code>ACTIVE = 1;</code>
     */
    ACTIVE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_BUSINESS_STATUS = 0;</code>
     */
    public static final int UNKNOWN_BUSINESS_STATUS_VALUE = 0;
    /**
     * <code>ACTIVE = 1;</code>
     */
    public static final int ACTIVE_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static BusinessStatus valueOf(int value) {
      return forNumber(value);
    }

    public static BusinessStatus forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_BUSINESS_STATUS;
        case 1: return ACTIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BusinessStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BusinessStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BusinessStatus>() {
            public BusinessStatus findValueByNumber(int number) {
              return BusinessStatus.forNumber(number);
            }
          };

    private final int value;

    private BusinessStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.entities.pb.BusinessStatus)
  }

  /**
   * Protobuf enum {@code com.entities.pb.SKUStatus}
   */
  public enum SKUStatus
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_KYU_STATUS = 0;</code>
     */
    UNKNOWN_KYU_STATUS(0),
    /**
     * <code>AVAILABLE = 1;</code>
     */
    AVAILABLE(1),
    /**
     * <code>UNAVAILABLE = 2;</code>
     */
    UNAVAILABLE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_KYU_STATUS = 0;</code>
     */
    public static final int UNKNOWN_KYU_STATUS_VALUE = 0;
    /**
     * <code>AVAILABLE = 1;</code>
     */
    public static final int AVAILABLE_VALUE = 1;
    /**
     * <code>UNAVAILABLE = 2;</code>
     */
    public static final int UNAVAILABLE_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static SKUStatus valueOf(int value) {
      return forNumber(value);
    }

    public static SKUStatus forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_KYU_STATUS;
        case 1: return AVAILABLE;
        case 2: return UNAVAILABLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SKUStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SKUStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SKUStatus>() {
            public SKUStatus findValueByNumber(int number) {
              return SKUStatus.forNumber(number);
            }
          };

    private final int value;

    private SKUStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.entities.pb.SKUStatus)
  }

  public interface StockKeepingUnitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.entities.pb.StockKeepingUnit)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string skuId = 1;</code>
     */
    String getSkuId();
    /**
     * <code>optional string skuId = 1;</code>
     */
    com.google.protobuf.ByteString
        getSkuIdBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string photo = 3;</code>
     */
    String getPhoto();
    /**
     * <code>optional string photo = 3;</code>
     */
    com.google.protobuf.ByteString
        getPhotoBytes();

    /**
     * <code>optional string brand = 4;</code>
     */
    String getBrand();
    /**
     * <code>optional string brand = 4;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>optional string subBrand = 5;</code>
     */
    String getSubBrand();
    /**
     * <code>optional string subBrand = 5;</code>
     */
    com.google.protobuf.ByteString
        getSubBrandBytes();

    /**
     * <code>optional string code = 6;</code>
     */
    String getCode();
    /**
     * <code>optional string code = 6;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>optional string description = 7;</code>
     */
    String getDescription();
    /**
     * <code>optional string description = 7;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional double unitPrice = 8;</code>
     */
    double getUnitPrice();

    /**
     * <code>optional .com.entities.pb.SKUStatus status = 9;</code>
     */
    int getStatusValue();
    /**
     * <code>optional .com.entities.pb.SKUStatus status = 9;</code>
     */
    SKUStatus getStatus();

    /**
     * <code>optional string createdBy = 10;</code>
     */
    String getCreatedBy();
    /**
     * <code>optional string createdBy = 10;</code>
     */
    com.google.protobuf.ByteString
        getCreatedByBytes();

    /**
     * <code>optional string category = 11;</code>
     */
    String getCategory();
    /**
     * <code>optional string category = 11;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>optional string unit = 12;</code>
     */
    String getUnit();
    /**
     * <code>optional string unit = 12;</code>
     */
    com.google.protobuf.ByteString
        getUnitBytes();
  }
  /**
   * Protobuf type {@code com.entities.pb.StockKeepingUnit}
   */
  public  static final class StockKeepingUnit extends
      com.google.protobuf.GeneratedMessageLite<
          StockKeepingUnit, StockKeepingUnit.Builder> implements
      // @@protoc_insertion_point(message_implements:com.entities.pb.StockKeepingUnit)
      StockKeepingUnitOrBuilder {
    private StockKeepingUnit() {
      skuId_ = "";
      name_ = "";
      photo_ = "";
      brand_ = "";
      subBrand_ = "";
      code_ = "";
      description_ = "";
      createdBy_ = "";
      category_ = "";
      unit_ = "";
    }
    public static final int SKUID_FIELD_NUMBER = 1;
    private String skuId_;
    /**
     * <code>optional string skuId = 1;</code>
     */
    public String getSkuId() {
      return skuId_;
    }
    /**
     * <code>optional string skuId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSkuIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(skuId_);
    }
    /**
     * <code>optional string skuId = 1;</code>
     */
    private void setSkuId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      skuId_ = value;
    }
    /**
     * <code>optional string skuId = 1;</code>
     */
    private void clearSkuId() {
      
      skuId_ = getDefaultInstance().getSkuId();
    }
    /**
     * <code>optional string skuId = 1;</code>
     */
    private void setSkuIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      skuId_ = value.toStringUtf8();
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private String name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public String getName() {
      return name_;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    private void setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>optional string name = 2;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int PHOTO_FIELD_NUMBER = 3;
    private String photo_;
    /**
     * <code>optional string photo = 3;</code>
     */
    public String getPhoto() {
      return photo_;
    }
    /**
     * <code>optional string photo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhotoBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(photo_);
    }
    /**
     * <code>optional string photo = 3;</code>
     */
    private void setPhoto(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      photo_ = value;
    }
    /**
     * <code>optional string photo = 3;</code>
     */
    private void clearPhoto() {
      
      photo_ = getDefaultInstance().getPhoto();
    }
    /**
     * <code>optional string photo = 3;</code>
     */
    private void setPhotoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      photo_ = value.toStringUtf8();
    }

    public static final int BRAND_FIELD_NUMBER = 4;
    private String brand_;
    /**
     * <code>optional string brand = 4;</code>
     */
    public String getBrand() {
      return brand_;
    }
    /**
     * <code>optional string brand = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(brand_);
    }
    /**
     * <code>optional string brand = 4;</code>
     */
    private void setBrand(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      brand_ = value;
    }
    /**
     * <code>optional string brand = 4;</code>
     */
    private void clearBrand() {
      
      brand_ = getDefaultInstance().getBrand();
    }
    /**
     * <code>optional string brand = 4;</code>
     */
    private void setBrandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      brand_ = value.toStringUtf8();
    }

    public static final int SUBBRAND_FIELD_NUMBER = 5;
    private String subBrand_;
    /**
     * <code>optional string subBrand = 5;</code>
     */
    public String getSubBrand() {
      return subBrand_;
    }
    /**
     * <code>optional string subBrand = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSubBrandBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(subBrand_);
    }
    /**
     * <code>optional string subBrand = 5;</code>
     */
    private void setSubBrand(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subBrand_ = value;
    }
    /**
     * <code>optional string subBrand = 5;</code>
     */
    private void clearSubBrand() {
      
      subBrand_ = getDefaultInstance().getSubBrand();
    }
    /**
     * <code>optional string subBrand = 5;</code>
     */
    private void setSubBrandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subBrand_ = value.toStringUtf8();
    }

    public static final int CODE_FIELD_NUMBER = 6;
    private String code_;
    /**
     * <code>optional string code = 6;</code>
     */
    public String getCode() {
      return code_;
    }
    /**
     * <code>optional string code = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(code_);
    }
    /**
     * <code>optional string code = 6;</code>
     */
    private void setCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      code_ = value;
    }
    /**
     * <code>optional string code = 6;</code>
     */
    private void clearCode() {
      
      code_ = getDefaultInstance().getCode();
    }
    /**
     * <code>optional string code = 6;</code>
     */
    private void setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      code_ = value.toStringUtf8();
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 7;
    private String description_;
    /**
     * <code>optional string description = 7;</code>
     */
    public String getDescription() {
      return description_;
    }
    /**
     * <code>optional string description = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(description_);
    }
    /**
     * <code>optional string description = 7;</code>
     */
    private void setDescription(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
    }
    /**
     * <code>optional string description = 7;</code>
     */
    private void clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
    }
    /**
     * <code>optional string description = 7;</code>
     */
    private void setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value.toStringUtf8();
    }

    public static final int UNITPRICE_FIELD_NUMBER = 8;
    private double unitPrice_;
    /**
     * <code>optional double unitPrice = 8;</code>
     */
    public double getUnitPrice() {
      return unitPrice_;
    }
    /**
     * <code>optional double unitPrice = 8;</code>
     */
    private void setUnitPrice(double value) {
      
      unitPrice_ = value;
    }
    /**
     * <code>optional double unitPrice = 8;</code>
     */
    private void clearUnitPrice() {
      
      unitPrice_ = 0D;
    }

    public static final int STATUS_FIELD_NUMBER = 9;
    private int status_;
    /**
     * <code>optional .com.entities.pb.SKUStatus status = 9;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .com.entities.pb.SKUStatus status = 9;</code>
     */
    public SKUStatus getStatus() {
      SKUStatus result = SKUStatus.forNumber(status_);
      return result == null ? SKUStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.entities.pb.SKUStatus status = 9;</code>
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>optional .com.entities.pb.SKUStatus status = 9;</code>
     */
    private void setStatus(SKUStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
    }
    /**
     * <code>optional .com.entities.pb.SKUStatus status = 9;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public static final int CREATEDBY_FIELD_NUMBER = 10;
    private String createdBy_;
    /**
     * <code>optional string createdBy = 10;</code>
     */
    public String getCreatedBy() {
      return createdBy_;
    }
    /**
     * <code>optional string createdBy = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedByBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(createdBy_);
    }
    /**
     * <code>optional string createdBy = 10;</code>
     */
    private void setCreatedBy(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdBy_ = value;
    }
    /**
     * <code>optional string createdBy = 10;</code>
     */
    private void clearCreatedBy() {
      
      createdBy_ = getDefaultInstance().getCreatedBy();
    }
    /**
     * <code>optional string createdBy = 10;</code>
     */
    private void setCreatedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdBy_ = value.toStringUtf8();
    }

    public static final int CATEGORY_FIELD_NUMBER = 11;
    private String category_;
    /**
     * <code>optional string category = 11;</code>
     */
    public String getCategory() {
      return category_;
    }
    /**
     * <code>optional string category = 11;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(category_);
    }
    /**
     * <code>optional string category = 11;</code>
     */
    private void setCategory(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      category_ = value;
    }
    /**
     * <code>optional string category = 11;</code>
     */
    private void clearCategory() {
      
      category_ = getDefaultInstance().getCategory();
    }
    /**
     * <code>optional string category = 11;</code>
     */
    private void setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      category_ = value.toStringUtf8();
    }

    public static final int UNIT_FIELD_NUMBER = 12;
    private String unit_;
    /**
     * <code>optional string unit = 12;</code>
     */
    public String getUnit() {
      return unit_;
    }
    /**
     * <code>optional string unit = 12;</code>
     */
    public com.google.protobuf.ByteString
        getUnitBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(unit_);
    }
    /**
     * <code>optional string unit = 12;</code>
     */
    private void setUnit(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      unit_ = value;
    }
    /**
     * <code>optional string unit = 12;</code>
     */
    private void clearUnit() {
      
      unit_ = getDefaultInstance().getUnit();
    }
    /**
     * <code>optional string unit = 12;</code>
     */
    private void setUnitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      unit_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!skuId_.isEmpty()) {
        output.writeString(1, getSkuId());
      }
      if (!name_.isEmpty()) {
        output.writeString(2, getName());
      }
      if (!photo_.isEmpty()) {
        output.writeString(3, getPhoto());
      }
      if (!brand_.isEmpty()) {
        output.writeString(4, getBrand());
      }
      if (!subBrand_.isEmpty()) {
        output.writeString(5, getSubBrand());
      }
      if (!code_.isEmpty()) {
        output.writeString(6, getCode());
      }
      if (!description_.isEmpty()) {
        output.writeString(7, getDescription());
      }
      if (unitPrice_ != 0D) {
        output.writeDouble(8, unitPrice_);
      }
      if (status_ != SKUStatus.UNKNOWN_KYU_STATUS.getNumber()) {
        output.writeEnum(9, status_);
      }
      if (!createdBy_.isEmpty()) {
        output.writeString(10, getCreatedBy());
      }
      if (!category_.isEmpty()) {
        output.writeString(11, getCategory());
      }
      if (!unit_.isEmpty()) {
        output.writeString(12, getUnit());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!skuId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSkuId());
      }
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (!photo_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getPhoto());
      }
      if (!brand_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getBrand());
      }
      if (!subBrand_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getSubBrand());
      }
      if (!code_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getCode());
      }
      if (!description_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getDescription());
      }
      if (unitPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, unitPrice_);
      }
      if (status_ != SKUStatus.UNKNOWN_KYU_STATUS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, status_);
      }
      if (!createdBy_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getCreatedBy());
      }
      if (!category_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(11, getCategory());
      }
      if (!unit_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(12, getUnit());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static StockKeepingUnit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static StockKeepingUnit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static StockKeepingUnit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static StockKeepingUnit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static StockKeepingUnit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static StockKeepingUnit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static StockKeepingUnit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static StockKeepingUnit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static StockKeepingUnit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static StockKeepingUnit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StockKeepingUnit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.entities.pb.StockKeepingUnit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          StockKeepingUnit, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.entities.pb.StockKeepingUnit)
        StockKeepingUnitOrBuilder {
      // Construct using com.treeleaf.suchi.entities.InventoryProto.StockKeepingUnit.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string skuId = 1;</code>
       */
      public String getSkuId() {
        return instance.getSkuId();
      }
      /**
       * <code>optional string skuId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSkuIdBytes() {
        return instance.getSkuIdBytes();
      }
      /**
       * <code>optional string skuId = 1;</code>
       */
      public Builder setSkuId(
          String value) {
        copyOnWrite();
        instance.setSkuId(value);
        return this;
      }
      /**
       * <code>optional string skuId = 1;</code>
       */
      public Builder clearSkuId() {
        copyOnWrite();
        instance.clearSkuId();
        return this;
      }
      /**
       * <code>optional string skuId = 1;</code>
       */
      public Builder setSkuIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSkuIdBytes(value);
        return this;
      }

      /**
       * <code>optional string name = 2;</code>
       */
      public String getName() {
        return instance.getName();
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>optional string photo = 3;</code>
       */
      public String getPhoto() {
        return instance.getPhoto();
      }
      /**
       * <code>optional string photo = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhotoBytes() {
        return instance.getPhotoBytes();
      }
      /**
       * <code>optional string photo = 3;</code>
       */
      public Builder setPhoto(
          String value) {
        copyOnWrite();
        instance.setPhoto(value);
        return this;
      }
      /**
       * <code>optional string photo = 3;</code>
       */
      public Builder clearPhoto() {
        copyOnWrite();
        instance.clearPhoto();
        return this;
      }
      /**
       * <code>optional string photo = 3;</code>
       */
      public Builder setPhotoBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPhotoBytes(value);
        return this;
      }

      /**
       * <code>optional string brand = 4;</code>
       */
      public String getBrand() {
        return instance.getBrand();
      }
      /**
       * <code>optional string brand = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        return instance.getBrandBytes();
      }
      /**
       * <code>optional string brand = 4;</code>
       */
      public Builder setBrand(
          String value) {
        copyOnWrite();
        instance.setBrand(value);
        return this;
      }
      /**
       * <code>optional string brand = 4;</code>
       */
      public Builder clearBrand() {
        copyOnWrite();
        instance.clearBrand();
        return this;
      }
      /**
       * <code>optional string brand = 4;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBrandBytes(value);
        return this;
      }

      /**
       * <code>optional string subBrand = 5;</code>
       */
      public String getSubBrand() {
        return instance.getSubBrand();
      }
      /**
       * <code>optional string subBrand = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSubBrandBytes() {
        return instance.getSubBrandBytes();
      }
      /**
       * <code>optional string subBrand = 5;</code>
       */
      public Builder setSubBrand(
          String value) {
        copyOnWrite();
        instance.setSubBrand(value);
        return this;
      }
      /**
       * <code>optional string subBrand = 5;</code>
       */
      public Builder clearSubBrand() {
        copyOnWrite();
        instance.clearSubBrand();
        return this;
      }
      /**
       * <code>optional string subBrand = 5;</code>
       */
      public Builder setSubBrandBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSubBrandBytes(value);
        return this;
      }

      /**
       * <code>optional string code = 6;</code>
       */
      public String getCode() {
        return instance.getCode();
      }
      /**
       * <code>optional string code = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        return instance.getCodeBytes();
      }
      /**
       * <code>optional string code = 6;</code>
       */
      public Builder setCode(
          String value) {
        copyOnWrite();
        instance.setCode(value);
        return this;
      }
      /**
       * <code>optional string code = 6;</code>
       */
      public Builder clearCode() {
        copyOnWrite();
        instance.clearCode();
        return this;
      }
      /**
       * <code>optional string code = 6;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCodeBytes(value);
        return this;
      }

      /**
       * <code>optional string description = 7;</code>
       */
      public String getDescription() {
        return instance.getDescription();
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        return instance.getDescriptionBytes();
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public Builder setDescription(
          String value) {
        copyOnWrite();
        instance.setDescription(value);
        return this;
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public Builder clearDescription() {
        copyOnWrite();
        instance.clearDescription();
        return this;
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDescriptionBytes(value);
        return this;
      }

      /**
       * <code>optional double unitPrice = 8;</code>
       */
      public double getUnitPrice() {
        return instance.getUnitPrice();
      }
      /**
       * <code>optional double unitPrice = 8;</code>
       */
      public Builder setUnitPrice(double value) {
        copyOnWrite();
        instance.setUnitPrice(value);
        return this;
      }
      /**
       * <code>optional double unitPrice = 8;</code>
       */
      public Builder clearUnitPrice() {
        copyOnWrite();
        instance.clearUnitPrice();
        return this;
      }

      /**
       * <code>optional .com.entities.pb.SKUStatus status = 9;</code>
       */
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>optional .com.entities.pb.SKUStatus status = 9;</code>
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>optional .com.entities.pb.SKUStatus status = 9;</code>
       */
      public SKUStatus getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>optional .com.entities.pb.SKUStatus status = 9;</code>
       */
      public Builder setStatus(SKUStatus value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>optional .com.entities.pb.SKUStatus status = 9;</code>
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>optional string createdBy = 10;</code>
       */
      public String getCreatedBy() {
        return instance.getCreatedBy();
      }
      /**
       * <code>optional string createdBy = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCreatedByBytes() {
        return instance.getCreatedByBytes();
      }
      /**
       * <code>optional string createdBy = 10;</code>
       */
      public Builder setCreatedBy(
          String value) {
        copyOnWrite();
        instance.setCreatedBy(value);
        return this;
      }
      /**
       * <code>optional string createdBy = 10;</code>
       */
      public Builder clearCreatedBy() {
        copyOnWrite();
        instance.clearCreatedBy();
        return this;
      }
      /**
       * <code>optional string createdBy = 10;</code>
       */
      public Builder setCreatedByBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCreatedByBytes(value);
        return this;
      }

      /**
       * <code>optional string category = 11;</code>
       */
      public String getCategory() {
        return instance.getCategory();
      }
      /**
       * <code>optional string category = 11;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        return instance.getCategoryBytes();
      }
      /**
       * <code>optional string category = 11;</code>
       */
      public Builder setCategory(
          String value) {
        copyOnWrite();
        instance.setCategory(value);
        return this;
      }
      /**
       * <code>optional string category = 11;</code>
       */
      public Builder clearCategory() {
        copyOnWrite();
        instance.clearCategory();
        return this;
      }
      /**
       * <code>optional string category = 11;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCategoryBytes(value);
        return this;
      }

      /**
       * <code>optional string unit = 12;</code>
       */
      public String getUnit() {
        return instance.getUnit();
      }
      /**
       * <code>optional string unit = 12;</code>
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        return instance.getUnitBytes();
      }
      /**
       * <code>optional string unit = 12;</code>
       */
      public Builder setUnit(
          String value) {
        copyOnWrite();
        instance.setUnit(value);
        return this;
      }
      /**
       * <code>optional string unit = 12;</code>
       */
      public Builder clearUnit() {
        copyOnWrite();
        instance.clearUnit();
        return this;
      }
      /**
       * <code>optional string unit = 12;</code>
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUnitBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.entities.pb.StockKeepingUnit)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new StockKeepingUnit();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          StockKeepingUnit other = (StockKeepingUnit) arg1;
          skuId_ = visitor.visitString(!skuId_.isEmpty(), skuId_,
              !other.skuId_.isEmpty(), other.skuId_);
          name_ = visitor.visitString(!name_.isEmpty(), name_,
              !other.name_.isEmpty(), other.name_);
          photo_ = visitor.visitString(!photo_.isEmpty(), photo_,
              !other.photo_.isEmpty(), other.photo_);
          brand_ = visitor.visitString(!brand_.isEmpty(), brand_,
              !other.brand_.isEmpty(), other.brand_);
          subBrand_ = visitor.visitString(!subBrand_.isEmpty(), subBrand_,
              !other.subBrand_.isEmpty(), other.subBrand_);
          code_ = visitor.visitString(!code_.isEmpty(), code_,
              !other.code_.isEmpty(), other.code_);
          description_ = visitor.visitString(!description_.isEmpty(), description_,
              !other.description_.isEmpty(), other.description_);
          unitPrice_ = visitor.visitDouble(unitPrice_ != 0D, unitPrice_,
              other.unitPrice_ != 0D, other.unitPrice_);
          status_ = visitor.visitInt(status_ != 0, status_,    other.status_ != 0, other.status_);
          createdBy_ = visitor.visitString(!createdBy_.isEmpty(), createdBy_,
              !other.createdBy_.isEmpty(), other.createdBy_);
          category_ = visitor.visitString(!category_.isEmpty(), category_,
              !other.category_.isEmpty(), other.category_);
          unit_ = visitor.visitString(!unit_.isEmpty(), unit_,
              !other.unit_.isEmpty(), other.unit_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  skuId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  photo_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  brand_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  subBrand_ = s;
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  code_ = s;
                  break;
                }
                case 58: {
                  String s = input.readStringRequireUtf8();

                  description_ = s;
                  break;
                }
                case 65: {

                  unitPrice_ = input.readDouble();
                  break;
                }
                case 72: {
                  int rawValue = input.readEnum();

                  status_ = rawValue;
                  break;
                }
                case 82: {
                  String s = input.readStringRequireUtf8();

                  createdBy_ = s;
                  break;
                }
                case 90: {
                  String s = input.readStringRequireUtf8();

                  category_ = s;
                  break;
                }
                case 98: {
                  String s = input.readStringRequireUtf8();

                  unit_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (StockKeepingUnit.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.entities.pb.StockKeepingUnit)
    private static final StockKeepingUnit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StockKeepingUnit();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static StockKeepingUnit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<StockKeepingUnit> PARSER;

    public static com.google.protobuf.Parser<StockKeepingUnit> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface InventoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.entities.pb.Inventory)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string inventoryId = 1;</code>
     */
    String getInventoryId();
    /**
     * <code>optional string inventoryId = 1;</code>
     */
    com.google.protobuf.ByteString
        getInventoryIdBytes();

    /**
     * <code>optional int32 quantity = 2;</code>
     */
    int getQuantity();

    /**
     * <code>optional int64 expiryDate = 3;</code>
     */
    long getExpiryDate();

    /**
     * <code>optional string skuId = 4;</code>
     */
    String getSkuId();
    /**
     * <code>optional string skuId = 4;</code>
     */
    com.google.protobuf.ByteString
        getSkuIdBytes();

    /**
     * <code>optional string userId = 5;</code>
     */
    String getUserId();
    /**
     * <code>optional string userId = 5;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();
  }
  /**
   * Protobuf type {@code com.entities.pb.Inventory}
   */
  public  static final class Inventory extends
      com.google.protobuf.GeneratedMessageLite<
          Inventory, Inventory.Builder> implements
      // @@protoc_insertion_point(message_implements:com.entities.pb.Inventory)
      InventoryOrBuilder {
    private Inventory() {
      inventoryId_ = "";
      skuId_ = "";
      userId_ = "";
    }
    public static final int INVENTORYID_FIELD_NUMBER = 1;
    private String inventoryId_;
    /**
     * <code>optional string inventoryId = 1;</code>
     */
    public String getInventoryId() {
      return inventoryId_;
    }
    /**
     * <code>optional string inventoryId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInventoryIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(inventoryId_);
    }
    /**
     * <code>optional string inventoryId = 1;</code>
     */
    private void setInventoryId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inventoryId_ = value;
    }
    /**
     * <code>optional string inventoryId = 1;</code>
     */
    private void clearInventoryId() {
      
      inventoryId_ = getDefaultInstance().getInventoryId();
    }
    /**
     * <code>optional string inventoryId = 1;</code>
     */
    private void setInventoryIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inventoryId_ = value.toStringUtf8();
    }

    public static final int QUANTITY_FIELD_NUMBER = 2;
    private int quantity_;
    /**
     * <code>optional int32 quantity = 2;</code>
     */
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>optional int32 quantity = 2;</code>
     */
    private void setQuantity(int value) {
      
      quantity_ = value;
    }
    /**
     * <code>optional int32 quantity = 2;</code>
     */
    private void clearQuantity() {
      
      quantity_ = 0;
    }

    public static final int EXPIRYDATE_FIELD_NUMBER = 3;
    private long expiryDate_;
    /**
     * <code>optional int64 expiryDate = 3;</code>
     */
    public long getExpiryDate() {
      return expiryDate_;
    }
    /**
     * <code>optional int64 expiryDate = 3;</code>
     */
    private void setExpiryDate(long value) {
      
      expiryDate_ = value;
    }
    /**
     * <code>optional int64 expiryDate = 3;</code>
     */
    private void clearExpiryDate() {
      
      expiryDate_ = 0L;
    }

    public static final int SKUID_FIELD_NUMBER = 4;
    private String skuId_;
    /**
     * <code>optional string skuId = 4;</code>
     */
    public String getSkuId() {
      return skuId_;
    }
    /**
     * <code>optional string skuId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSkuIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(skuId_);
    }
    /**
     * <code>optional string skuId = 4;</code>
     */
    private void setSkuId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      skuId_ = value;
    }
    /**
     * <code>optional string skuId = 4;</code>
     */
    private void clearSkuId() {
      
      skuId_ = getDefaultInstance().getSkuId();
    }
    /**
     * <code>optional string skuId = 4;</code>
     */
    private void setSkuIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      skuId_ = value.toStringUtf8();
    }

    public static final int USERID_FIELD_NUMBER = 5;
    private String userId_;
    /**
     * <code>optional string userId = 5;</code>
     */
    public String getUserId() {
      return userId_;
    }
    /**
     * <code>optional string userId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userId_);
    }
    /**
     * <code>optional string userId = 5;</code>
     */
    private void setUserId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
    }
    /**
     * <code>optional string userId = 5;</code>
     */
    private void clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
    }
    /**
     * <code>optional string userId = 5;</code>
     */
    private void setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!inventoryId_.isEmpty()) {
        output.writeString(1, getInventoryId());
      }
      if (quantity_ != 0) {
        output.writeInt32(2, quantity_);
      }
      if (expiryDate_ != 0L) {
        output.writeInt64(3, expiryDate_);
      }
      if (!skuId_.isEmpty()) {
        output.writeString(4, getSkuId());
      }
      if (!userId_.isEmpty()) {
        output.writeString(5, getUserId());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!inventoryId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getInventoryId());
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, quantity_);
      }
      if (expiryDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, expiryDate_);
      }
      if (!skuId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getSkuId());
      }
      if (!userId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getUserId());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static Inventory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Inventory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Inventory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Inventory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Inventory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Inventory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Inventory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Inventory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Inventory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Inventory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Inventory prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.entities.pb.Inventory}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Inventory, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.entities.pb.Inventory)
        InventoryOrBuilder {
      // Construct using com.treeleaf.suchi.entities.InventoryProto.Inventory.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string inventoryId = 1;</code>
       */
      public String getInventoryId() {
        return instance.getInventoryId();
      }
      /**
       * <code>optional string inventoryId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getInventoryIdBytes() {
        return instance.getInventoryIdBytes();
      }
      /**
       * <code>optional string inventoryId = 1;</code>
       */
      public Builder setInventoryId(
          String value) {
        copyOnWrite();
        instance.setInventoryId(value);
        return this;
      }
      /**
       * <code>optional string inventoryId = 1;</code>
       */
      public Builder clearInventoryId() {
        copyOnWrite();
        instance.clearInventoryId();
        return this;
      }
      /**
       * <code>optional string inventoryId = 1;</code>
       */
      public Builder setInventoryIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setInventoryIdBytes(value);
        return this;
      }

      /**
       * <code>optional int32 quantity = 2;</code>
       */
      public int getQuantity() {
        return instance.getQuantity();
      }
      /**
       * <code>optional int32 quantity = 2;</code>
       */
      public Builder setQuantity(int value) {
        copyOnWrite();
        instance.setQuantity(value);
        return this;
      }
      /**
       * <code>optional int32 quantity = 2;</code>
       */
      public Builder clearQuantity() {
        copyOnWrite();
        instance.clearQuantity();
        return this;
      }

      /**
       * <code>optional int64 expiryDate = 3;</code>
       */
      public long getExpiryDate() {
        return instance.getExpiryDate();
      }
      /**
       * <code>optional int64 expiryDate = 3;</code>
       */
      public Builder setExpiryDate(long value) {
        copyOnWrite();
        instance.setExpiryDate(value);
        return this;
      }
      /**
       * <code>optional int64 expiryDate = 3;</code>
       */
      public Builder clearExpiryDate() {
        copyOnWrite();
        instance.clearExpiryDate();
        return this;
      }

      /**
       * <code>optional string skuId = 4;</code>
       */
      public String getSkuId() {
        return instance.getSkuId();
      }
      /**
       * <code>optional string skuId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSkuIdBytes() {
        return instance.getSkuIdBytes();
      }
      /**
       * <code>optional string skuId = 4;</code>
       */
      public Builder setSkuId(
          String value) {
        copyOnWrite();
        instance.setSkuId(value);
        return this;
      }
      /**
       * <code>optional string skuId = 4;</code>
       */
      public Builder clearSkuId() {
        copyOnWrite();
        instance.clearSkuId();
        return this;
      }
      /**
       * <code>optional string skuId = 4;</code>
       */
      public Builder setSkuIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSkuIdBytes(value);
        return this;
      }

      /**
       * <code>optional string userId = 5;</code>
       */
      public String getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>optional string userId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        return instance.getUserIdBytes();
      }
      /**
       * <code>optional string userId = 5;</code>
       */
      public Builder setUserId(
          String value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>optional string userId = 5;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }
      /**
       * <code>optional string userId = 5;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.entities.pb.Inventory)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Inventory();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Inventory other = (Inventory) arg1;
          inventoryId_ = visitor.visitString(!inventoryId_.isEmpty(), inventoryId_,
              !other.inventoryId_.isEmpty(), other.inventoryId_);
          quantity_ = visitor.visitInt(quantity_ != 0, quantity_,
              other.quantity_ != 0, other.quantity_);
          expiryDate_ = visitor.visitLong(expiryDate_ != 0L, expiryDate_,
              other.expiryDate_ != 0L, other.expiryDate_);
          skuId_ = visitor.visitString(!skuId_.isEmpty(), skuId_,
              !other.skuId_.isEmpty(), other.skuId_);
          userId_ = visitor.visitString(!userId_.isEmpty(), userId_,
              !other.userId_.isEmpty(), other.userId_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  inventoryId_ = s;
                  break;
                }
                case 16: {

                  quantity_ = input.readInt32();
                  break;
                }
                case 24: {

                  expiryDate_ = input.readInt64();
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  skuId_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  userId_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Inventory.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.entities.pb.Inventory)
    private static final Inventory DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Inventory();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Inventory getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Inventory> PARSER;

    public static com.google.protobuf.Parser<Inventory> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LicenseKeyManagementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.entities.pb.LicenseKeyManagement)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string licenseKey = 1;</code>
     */
    String getLicenseKey();
    /**
     * <code>optional string licenseKey = 1;</code>
     */
    com.google.protobuf.ByteString
        getLicenseKeyBytes();

    /**
     * <code>optional string panVat = 2;</code>
     */
    String getPanVat();
    /**
     * <code>optional string panVat = 2;</code>
     */
    com.google.protobuf.ByteString
        getPanVatBytes();

    /**
     * <code>optional int64 assignedDate = 3;</code>
     */
    long getAssignedDate();

    /**
     * <code>optional int64 expiryDate = 4;</code>
     */
    long getExpiryDate();
  }
  /**
   * Protobuf type {@code com.entities.pb.LicenseKeyManagement}
   */
  public  static final class LicenseKeyManagement extends
      com.google.protobuf.GeneratedMessageLite<
          LicenseKeyManagement, LicenseKeyManagement.Builder> implements
      // @@protoc_insertion_point(message_implements:com.entities.pb.LicenseKeyManagement)
      LicenseKeyManagementOrBuilder {
    private LicenseKeyManagement() {
      licenseKey_ = "";
      panVat_ = "";
    }
    public static final int LICENSEKEY_FIELD_NUMBER = 1;
    private String licenseKey_;
    /**
     * <code>optional string licenseKey = 1;</code>
     */
    public String getLicenseKey() {
      return licenseKey_;
    }
    /**
     * <code>optional string licenseKey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLicenseKeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(licenseKey_);
    }
    /**
     * <code>optional string licenseKey = 1;</code>
     */
    private void setLicenseKey(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      licenseKey_ = value;
    }
    /**
     * <code>optional string licenseKey = 1;</code>
     */
    private void clearLicenseKey() {
      
      licenseKey_ = getDefaultInstance().getLicenseKey();
    }
    /**
     * <code>optional string licenseKey = 1;</code>
     */
    private void setLicenseKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      licenseKey_ = value.toStringUtf8();
    }

    public static final int PANVAT_FIELD_NUMBER = 2;
    private String panVat_;
    /**
     * <code>optional string panVat = 2;</code>
     */
    public String getPanVat() {
      return panVat_;
    }
    /**
     * <code>optional string panVat = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPanVatBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(panVat_);
    }
    /**
     * <code>optional string panVat = 2;</code>
     */
    private void setPanVat(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      panVat_ = value;
    }
    /**
     * <code>optional string panVat = 2;</code>
     */
    private void clearPanVat() {
      
      panVat_ = getDefaultInstance().getPanVat();
    }
    /**
     * <code>optional string panVat = 2;</code>
     */
    private void setPanVatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      panVat_ = value.toStringUtf8();
    }

    public static final int ASSIGNEDDATE_FIELD_NUMBER = 3;
    private long assignedDate_;
    /**
     * <code>optional int64 assignedDate = 3;</code>
     */
    public long getAssignedDate() {
      return assignedDate_;
    }
    /**
     * <code>optional int64 assignedDate = 3;</code>
     */
    private void setAssignedDate(long value) {
      
      assignedDate_ = value;
    }
    /**
     * <code>optional int64 assignedDate = 3;</code>
     */
    private void clearAssignedDate() {
      
      assignedDate_ = 0L;
    }

    public static final int EXPIRYDATE_FIELD_NUMBER = 4;
    private long expiryDate_;
    /**
     * <code>optional int64 expiryDate = 4;</code>
     */
    public long getExpiryDate() {
      return expiryDate_;
    }
    /**
     * <code>optional int64 expiryDate = 4;</code>
     */
    private void setExpiryDate(long value) {
      
      expiryDate_ = value;
    }
    /**
     * <code>optional int64 expiryDate = 4;</code>
     */
    private void clearExpiryDate() {
      
      expiryDate_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!licenseKey_.isEmpty()) {
        output.writeString(1, getLicenseKey());
      }
      if (!panVat_.isEmpty()) {
        output.writeString(2, getPanVat());
      }
      if (assignedDate_ != 0L) {
        output.writeInt64(3, assignedDate_);
      }
      if (expiryDate_ != 0L) {
        output.writeInt64(4, expiryDate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!licenseKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getLicenseKey());
      }
      if (!panVat_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPanVat());
      }
      if (assignedDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, assignedDate_);
      }
      if (expiryDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, expiryDate_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static LicenseKeyManagement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LicenseKeyManagement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LicenseKeyManagement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LicenseKeyManagement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LicenseKeyManagement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LicenseKeyManagement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LicenseKeyManagement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static LicenseKeyManagement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LicenseKeyManagement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LicenseKeyManagement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LicenseKeyManagement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code com.entities.pb.LicenseKeyManagement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          LicenseKeyManagement, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.entities.pb.LicenseKeyManagement)
        LicenseKeyManagementOrBuilder {
      // Construct using com.treeleaf.suchi.entities.InventoryProto.LicenseKeyManagement.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string licenseKey = 1;</code>
       */
      public String getLicenseKey() {
        return instance.getLicenseKey();
      }
      /**
       * <code>optional string licenseKey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLicenseKeyBytes() {
        return instance.getLicenseKeyBytes();
      }
      /**
       * <code>optional string licenseKey = 1;</code>
       */
      public Builder setLicenseKey(
          String value) {
        copyOnWrite();
        instance.setLicenseKey(value);
        return this;
      }
      /**
       * <code>optional string licenseKey = 1;</code>
       */
      public Builder clearLicenseKey() {
        copyOnWrite();
        instance.clearLicenseKey();
        return this;
      }
      /**
       * <code>optional string licenseKey = 1;</code>
       */
      public Builder setLicenseKeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLicenseKeyBytes(value);
        return this;
      }

      /**
       * <code>optional string panVat = 2;</code>
       */
      public String getPanVat() {
        return instance.getPanVat();
      }
      /**
       * <code>optional string panVat = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPanVatBytes() {
        return instance.getPanVatBytes();
      }
      /**
       * <code>optional string panVat = 2;</code>
       */
      public Builder setPanVat(
          String value) {
        copyOnWrite();
        instance.setPanVat(value);
        return this;
      }
      /**
       * <code>optional string panVat = 2;</code>
       */
      public Builder clearPanVat() {
        copyOnWrite();
        instance.clearPanVat();
        return this;
      }
      /**
       * <code>optional string panVat = 2;</code>
       */
      public Builder setPanVatBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPanVatBytes(value);
        return this;
      }

      /**
       * <code>optional int64 assignedDate = 3;</code>
       */
      public long getAssignedDate() {
        return instance.getAssignedDate();
      }
      /**
       * <code>optional int64 assignedDate = 3;</code>
       */
      public Builder setAssignedDate(long value) {
        copyOnWrite();
        instance.setAssignedDate(value);
        return this;
      }
      /**
       * <code>optional int64 assignedDate = 3;</code>
       */
      public Builder clearAssignedDate() {
        copyOnWrite();
        instance.clearAssignedDate();
        return this;
      }

      /**
       * <code>optional int64 expiryDate = 4;</code>
       */
      public long getExpiryDate() {
        return instance.getExpiryDate();
      }
      /**
       * <code>optional int64 expiryDate = 4;</code>
       */
      public Builder setExpiryDate(long value) {
        copyOnWrite();
        instance.setExpiryDate(value);
        return this;
      }
      /**
       * <code>optional int64 expiryDate = 4;</code>
       */
      public Builder clearExpiryDate() {
        copyOnWrite();
        instance.clearExpiryDate();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.entities.pb.LicenseKeyManagement)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new LicenseKeyManagement();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          LicenseKeyManagement other = (LicenseKeyManagement) arg1;
          licenseKey_ = visitor.visitString(!licenseKey_.isEmpty(), licenseKey_,
              !other.licenseKey_.isEmpty(), other.licenseKey_);
          panVat_ = visitor.visitString(!panVat_.isEmpty(), panVat_,
              !other.panVat_.isEmpty(), other.panVat_);
          assignedDate_ = visitor.visitLong(assignedDate_ != 0L, assignedDate_,
              other.assignedDate_ != 0L, other.assignedDate_);
          expiryDate_ = visitor.visitLong(expiryDate_ != 0L, expiryDate_,
              other.expiryDate_ != 0L, other.expiryDate_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  licenseKey_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  panVat_ = s;
                  break;
                }
                case 24: {

                  assignedDate_ = input.readInt64();
                  break;
                }
                case 32: {

                  expiryDate_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (LicenseKeyManagement.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.entities.pb.LicenseKeyManagement)
    private static final LicenseKeyManagement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LicenseKeyManagement();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static LicenseKeyManagement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LicenseKeyManagement> PARSER;

    public static com.google.protobuf.Parser<LicenseKeyManagement> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
